/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'primary':                  '#032417',
        'primary-container':        '#1a3a2b',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#82a491',
        'secondary':                '#516600',
        'secondary-container':      '#c7ef48',
        'on-secondary-container':   '#546b00',
        'on-secondary':             '#ffffff',
        'tertiary':                 '#192200',
        'tertiary-fixed':           '#caf24b',
        'tertiary-fixed-dim':       '#aed52e',
        'secondary-fixed-dim':      '#aed52e',
        'secondary-fixed':          '#caf24b',
        'surface':                  '#fdf9f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f7f3ec',
        'surface-container':        '#f1ede6',
        'surface-container-high':   '#ebe8e1',
        'surface-container-highest':'#e6e2db',
        'surface-bright':           '#fdf9f2',
        'surface-dim':              '#dddad3',
        'on-surface':               '#1c1c18',
        'on-surface-variant':       '#424844',
        'outline':                  '#727973',
        'outline-variant':          '#c1c8c2',
        'background':               '#fdf9f2',
        'on-background':            '#1c1c18',
        'inverse-surface':          '#31302c',
        'inverse-on-surface':       '#f4f0e9',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'surface-variant':          '#e6e2db',
        'surface-tint':             '#456554',
        'primary-fixed':            '#c7ebd5',
        'primary-fixed-dim':        '#abcfba',
        'inverse-primary':          '#abcfba',
      },
      fontFamily: {
        'headline': ['NotoSerif_400Regular'],
        'headline-bold': ['NotoSerif_700Bold'],
        'headline-italic': ['NotoSerif_400Regular_Italic'],
        'headline-bold-italic': ['NotoSerif_700Bold_Italic'],
        'body': ['Manrope_400Regular'],
        'body-medium': ['Manrope_500Medium'],
        'body-semibold': ['Manrope_600SemiBold'],
        'body-bold': ['Manrope_700Bold'],
        'body-extrabold': ['Manrope_800ExtraBold'],
        'label': ['Manrope_400Regular'],
      },
    },
  },
  plugins: [],
};
