-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: Migrate chains table to full catalog with pattern matching
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Add new columns (chain_id slug + regex pattern)
ALTER TABLE public.chains ADD COLUMN IF NOT EXISTS chain_id TEXT UNIQUE;
ALTER TABLE public.chains ADD COLUMN IF NOT EXISTS pattern  TEXT;

-- 2. Clear old data (was incomplete/stale)
TRUNCATE public.chains CASCADE;

-- 3. Insert the full catalog (128 entries)
INSERT INTO public.chains (chain_id, name, pattern) VALUES
  -- FAST FOOD — HAMBURGUESAS INTERNACIONALES
  ('mcdonalds',           'McDonald''s',                    'mcdonald'),
  ('burger-king',         'Burger King',                    'burger\s*king'),
  ('kfc',                 'KFC',                            '\bkfc\b'),
  ('five-guys',           'Five Guys',                      'five\s*guys'),
  ('carls-jr',            'Carl''s Jr.',                    'carl.s\s*jr'),
  ('popeyes',             'Popeyes',                        'popeyes'),
  ('wendys',              'Wendy''s',                       'wendy.s'),
  ('wingstop',            'Wingstop',                       'wingstop'),
  ('pollo-campero',       'Pollo Campero',                  'pollo\s*campero'),
  -- FAST FOOD — HAMBURGUESAS ESPAÑOLAS / GOURMET
  ('goiko',               'Goiko',                          '\bgoiko\b'),
  ('tgb',                 'TGB – The Good Burger',          '\btgb\b|the\s*good\s*burger'),
  ('bacoa',               'Bacoa',                          '\bbacoa\b'),
  ('la-pepita',           'La Pepita Burger Bar',           'la\s*pepita'),
  ('frankie-burgers',     'Frankie Burgers',                'frankie\s*burger'),
  ('vicio',               'Vicio',                          '\bvicio\b'),
  ('hamburguesa-nostra',  'Hamburguesa Nostra',             'hamburguesa\s*nostra'),
  ('new-york-burger',     'New York Burger',                'new\s*york\s*burger'),
  ('timesburg',           'Timesburg',                      'timesburg'),
  ('toro-burger',         'TORO Burger Lounge',             'toro\s*burger'),
  ('bertys',              'Berty''s',                       '\bberty.s\b'),
  ('hundred-burgers',     'Hundred Burgers',                '\bhundreds?\b'),
  -- FAST FOOD — PIZZA
  ('telepizza',           'Telepizza',                      'telepizza'),
  ('dominos',             'Domino''s Pizza',                'domino.s'),
  ('pizza-hut',           'Pizza Hut',                      'pizza\s*hut'),
  ('papa-johns',          'Papa John''s',                   'papa\s*john'),
  ('grosso-napoletano',   'Grosso Napoletano',              'grosso\s*napoleon'),
  ('fratelli-figurato',   'Fratelli Figurato',              'fratelli\s*figurato'),
  ('papizza',             'Papizza',                        'papizza'),
  -- FAST FOOD — OTROS
  ('subway',              'Subway',                         '\bsubway\b'),
  ('taco-bell',           'Taco Bell',                      'taco\s*bell'),
  ('dunkin',              'Dunkin''',                       'dunkin'),
  ('pans-company',        'Pans & Company',                 'pans\s*[&y]?\s*company'),
  ('rodilla',             'Rodilla',                        '\brodilla\b'),
  ('bocatta',             'Bocatta',                        '\bbocatta\b'),
  -- CASUAL DINING — AMERICANO / DINER
  ('vips',                'VIPS',                           '\bvips\b'),
  ('fosters-hollywood',   'Foster''s Hollywood',            'foster.s\s*hollywood'),
  ('100-montaditos',      '100 Montaditos',                 '100\s*montaditos'),
  ('la-surena',           'La Sureña',                      'la\s*sure[ñn]a'),
  ('tony-romas',          'Tony Roma''s',                   'tony\s*roma'),
  ('tgi-fridays',         'TGI Friday''s',                  'tgi\s*friday|friday.s'),
  ('hard-rock-cafe',      'Hard Rock Cafe',                 'hard\s*rock\s*caf[eé]'),
  ('tommy-mels',          'Tommy Mel''s',                   'tommy\s*mel'),
  ('peggy-sues',          'Peggy Sue''s',                   'peggy\s*sue'),
  -- CASUAL DINING — ITALIANO
  ('la-tagliatella',      'La Tagliatella',                 'la\s*tagliatella'),
  ('ginos',               'Ginos',                          '\bginos\b'),
  ('pomodoro',            'Pomodoro',                       '\bpomodoro\b'),
  ('vezzo',               'Vezzo',                          '\bvezzo\b'),
  ('muerde-la-pasta',     'Muerde la Pasta',                'muerde\s*la\s*pasta'),
  ('la-mafia',            'La Mafia se sienta a la mesa',   'la\s*mafia'),
  -- CASUAL DINING — TAPAS Y ESPAÑOL TRADICIONAL
  ('la-monarracha',       'La Monarracha',                  'monarracha'),
  ('lateral',             'Lateral',                        '\blateral\b'),
  ('la-maruca',           'La Maruca',                      'la\s*maruca'),
  ('taberna-volapie',     'Taberna del Volapié',            'volapi[eé]'),
  ('lizarran',            'Lizarran',                       'lizarran'),
  ('canas-y-tapas',       'Cañas y Tapas',                  'ca[ñn]as\s*y\s*tapas'),
  ('barra-de-pintxos',    'BaRRa de Pintxos',               'barra\s*de\s*pintxos'),
  ('celso-y-manolo',      'Celso y Manolo',                 'celso\s*y\s*manolo'),
  ('arzabal',             'Arzábal',                        'arz[aá]bal'),
  ('mercado-reina',       'Mercado de la Reina',            'mercado\s*de\s*la\s*reina'),
  ('masqmenos',           'MásQMenos',                      'm[aá]sqmenos|m[aá]s\s*que?\s*menos'),
  ('cantina-mariachi',    'Cantina Mariachi',               'cantina\s*mariachi'),
  ('taberna-la-daniela',  'Taberna La Daniela',             'taberna\s*la\s*daniela'),
  ('asador-aranda',       'Asador de Aranda',               'asador\s*de\s*aranda'),
  ('ojala',               'Ojalá',                          '\bojal[aá]\b'),
  ('dehesa-santa-maria',  'Dehesa Santa María',             'dehesa\s*santa\s*mar[ií]a'),
  ('el-kiosko',           'El Kiosko',                      '\bel\s*kiosko\b'),
  ('museo-del-jamon',     'Museo del Jamón',                'museo\s*del\s*jam[oó]n'),
  ('cinco-jotas',         'Mesón Cinco Jotas',              'cinco\s*jotas|5\s*j\b'),
  ('taller-de-tapas',     'Taller de Tapas',                'taller\s*de\s*tapas'),
  ('tapas-24',            'Tapas 24',                       'tapas\s*24'),
  ('lamucca',             'Lamucca',                        '\blamucca\b'),
  ('la-mordida',          'La Mordida',                     'la\s*mordida'),
  ('pura-brasa',          'Pura Brasa',                     'pura\s*brasa'),
  -- COCINA SALUDABLE
  ('honest-greens',       'Honest Greens',                  'honest\s*green'),
  ('flax-kale',           'Flax & Kale',                    'flax\s*[&y]\s*kale'),
  ('teresa-carles',       'Teresa Carles',                  'teresa\s*carles'),
  ('fresco',              'FrescCo',                        '\bfresc\s*co\b'),
  -- POKE BOWLS
  ('aloha-poke',          'Aloha Poke',                     'aloha\s*poke'),
  ('poke-house',          'Poke House',                     'poke\s*house'),
  ('tasty-poke',          'Tasty Poke Bar',                 'tasty\s*poke'),
  ('ohana-poke',          'Ohana Poke House',               'ohana\s*poke'),
  ('healthy-poke',        'Healthy Poke',                   'healthy\s*poke'),
  ('mahalo-poke',         'Mahalo Poké',                    'mahalo\s*pok[eé]'),
  -- COCINA ASIÁTICA
  ('udon',                'UDON',                           '\budon\b'),
  ('wagamama',            'Wagamama',                       'wagamama'),
  ('miss-sushi',          'Miss Sushi',                     'miss\s*sushi'),
  ('sushisom',            'Sushisom',                       'sushisom'),
  ('sushi-shop',          'Sushi Shop',                     'sushi\s*shop'),
  ('kanbun',              'Kanbun',                         'kanbun'),
  ('sibuya',              'Sibuya Urban Sushi Bar',         '\bsibuya\b'),
  ('ramen-shifu',         'Ramen Shifu',                    'ramen\s*shifu'),
  ('ramen-kagura',        'Ramen Kagura',                   'ramen\s*kagura'),
  ('wok-to-walk',         'Wok to Walk',                    'wok\s*to\s*walk'),
  ('tuk-tuk',             'Tuk Tuk Asian Street Food',      'tuk\s*tuk'),
  ('makitake',            'Makitake',                       'makitake'),
  ('sushita',             'Sushita',                        'sushita'),
  ('sumo',                'Sumo',                           '\bsumo\b'),
  ('ikibana',             'Ikibana',                        'ikibana'),
  ('padthaiwok',          'Padthaiwok',                     'padthaiwok|pad\s*thai\s*wok'),
  ('boa-bao',             'Boa-Bao',                        'boa[\s-]*bao'),
  ('lamonarracha',        'Lamonarracha',                   'la\s*monarracha'),
  -- CAFÉ, BAKERY Y DESAYUNOS
  ('starbucks',           'Starbucks',                      'starbucks'),
  ('tim-hortons',         'Tim Hortons',                    'tim\s*horton'),
  ('santagloria',         'Santagloria',                    'santagloria'),
  ('granier',             'Granier',                        '\bgranier\b'),
  ('panaria',             'Panaria',                        '\bpanaria\b'),
  ('cafe-y-te',           'Café & Té',                      'caf[eé]\s*[&y]\s*t[eé]'),
  ('manolo-bakes',        'Manolo Bakes',                   'manolo\s*bakes'),
  ('levaduramadre',       'Levaduramadre',                  'levaduramadre'),
  ('le-pain-quotidien',   'Le Pain Quotidien',              'le\s*pain\s*quotidien'),
  ('lobrador',            'L''Obrador',                     'l[''']obrador'),
  ('viena',               'Viena',                          '\bviena\b'),
  ('brunch-and-cake',     'Brunch & Cake',                  'brunch\s*[&y]\s*cake'),
  ('celicioso',           'Celicioso',                      'celicioso'),
  ('alsur-cafe',          'Alsur Café',                     'alsur\s*caf[eé]'),
  ('krispy-kreme',        'Krispy Kreme',                   'krispy\s*kreme'),
  ('wowble',              'Wowble!',                        'wowble'),
  -- HELADOS Y POSTRES
  ('llaollao',            'Llaollao',                       'llaollao'),
  ('smooy',               'Smöoy',                          'sm[oö]+y'),
  ('haagen-dazs',         'Häagen-Dazs',                    'h[aä]agen.dazs'),
  ('amorino',             'Amorino',                        '\bamorino\b'),
  -- OTROS
  ('la-chelinda',         'La Chelinda',                    'la\s*chelinda'),
  ('kurz-und-gut',        'Kurz & Gut',                     'kurz'),
  ('taco-alto',           'Taco Alto',                      'taco\s*alto'),
  ('sagardi',             'Sagardi',                        '\bsagardi\b'),
  ('irati',               'Irati',                          '\birati\b'),
  ('blue-frog',           'Blue Frog',                      'blue\s*frog')
ON CONFLICT (chain_id) DO UPDATE SET
  name    = EXCLUDED.name,
  pattern = EXCLUDED.pattern;
